ARG BASE_IMAGE=debian:trixie-slim
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        build-essential \
        ca-certificates \
        curl \
        dtach \
        file \
        git \
        gnupg \
        htop \
        iputils-ping \
        jq \
        less \
        locales \
        lsb-release \
        lsof \
        openssh-client \
        procps \
        python3 \
        rsync \
        software-properties-common \
        strace \
        sudo \
        tar \
        tree \
        unzip \
        vim \
        wget && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
